### ISSUE TITLE
App version too low. Please upgrade

### ISSUE THREAD

**Issue by k19862217** [MoomooOpen/py-moomoo-api#4]
I am using moomoo_OpenD_8.1.4108_Ubuntu16.04 binary to login, but it raised error like this:
```
moomoo OpenD version: 8.1.4108(20240229115000)
Start Time: 2024-04-16 06:39:18
moomoo OpenD is running
Load configuration file successfully
Server startup
API Listening Address: 127.0.0.1:11111
API RSA Enable: No
Login Method: Account password login
Logging in
Login failed,App version too low. Please upgrade
Login failed
moomoo OpenD exited
```

I think I am using the latest version, could you please help me out?
Thank you.

**Comment by MoomooOpen** [comment]
Hi, Currently Moomoo API not supports for users in Japan and Australia and Malaysia.

If you are not in this area, please package the log directory and send it to us.

Windows：%appdata%/com.futunn.FutuOpenD/Log

Not Windows：~/.com.futunn.FutuOpenD/Log

发件人: ***@***.*** ***@***.***> 代表 k19862217
发送时间: 2024年4月16日 6:42
收件人: MoomooOpen/py-moomoo-api ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MoomooOpen/py-moomoo-api] App version too low. Please upgrade (Issue #4)

 

I am using moomoo_OpenD_8.1.4108_Ubuntu16.04 binary to login, but it raised error like this:

moomoo OpenD version: 8.1.4108(20240229115000)
Start Time: 2024-04-16 06:39:18
moomoo OpenD is running
Load configuration file successfully
Server startup
API Listening Address: 127.0.0.1:11111
API RSA Enable: No
Login Method: Account password login
Logging in
Login failed,App version too low. Please upgrade
Login failed
moomoo OpenD exited

I think I am using the latest version, could you please help me out?
Thank you.
