### ISSUE TITLE
position_list_query not working

### ISSUE THREAD

**Issue by cometta** [MoomooOpen/py-moomoo-api#7]
below is python code
```
position_list_query(code='', pl_ratio_min=None, pl_ratio_max=None, trd_env=TrdEnv.REAL, acc_id=0, acc_index=-0, refresh_cache=True)
```

i able to retrieve US stock that i purchased , but not SG stocks. can advice?

Does `TrdMarket` variable has value for SG ?

**Comment by byblehua** [comment]
OpenAPI does not yet support stock trading in the SG market
